name 'rat/javatools'
version '0.1.0'
source 'UNKNOWN'
author 'Richard Attermeyer'
license 'Apache License, Version 2.0'
summary 'Installs Jetbrains IntelliJ'
description 'Installs some JavaTools'
project_page 'UNKNOWN'
## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'